apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-microservice
spec:
  selector:
    matchLabels:
      app: users-deployment
  template:
    metadata:
      labels:
        app: users-deployment
    spec:
      containers:
      - name: user-microservice-app-1
        image: user-microservice-app:latest
        imagePullPolicy: Always
        ports:
        - name: http
          containerPort: 5000
          protocol: TCP